[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
solc = "0.8.20"
evm_version = "paris"

[profile.default.optimizer]
enabled = true
runs = 200

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
