[profile.default]
src = "src"
out = "out"
libs = ["../lib"]
test = "test"
cache_path = "cache"

solc_version = "0.8.20"
evm_version = "shanghai"
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
